### ISSUE TITLE
including ng-electron.js causes error "Uncaught Error: Cannot find module 'diskdb'"

### ISSUE THREAD

**Issue by dorgan** [develephant/ngElectron#6]
Simple putting ng-electron.js in an application is causing the following error:

"Uncaught Error: Cannot find module 'diskdb'"

I think this is because ng-electron is expecting diskdb to be setup, but there are no details on how to configure this dependancy.

**Comment by ArekSredzki** [comment]
:+1:

**Comment by rafaelvieiras** [comment]
I have the same problem.
I fixed this fast and temporary with "npm install diskdb --save" in electron project. But, the ideal is make a validation if diskdb is installed or not.

**Comment by matheusgrieger** [comment]
I'm getting this error as well, would like to know how to solve it.

**Comment by dorgan** [comment]
Legate the resolution to this?

**Comment by dorgan** [comment]
*whats the resolution to this?

**Comment by matheusgrieger** [comment]
Looking at the latest commit, DiskDB was removed.
